#!/bin/bash

PLUGIN_DIR="~/.config/sketchybar/plugins"

sketchybar --bar position=top height=32 blur_radius=30 color=0xFF000000
sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_mode

default=(
  padding_left=5
  padding_right=5
  icon.font="SF Pro:Semibold:14.0"
  label.font="SF Pro:Semibold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)

sketchybar --default "${default[@]}"

# Left side items
sketchybar --add item space left \
	       --set space script="$PLUGIN_DIR/aerospace.sh" \
		   --subscribe space aerospace_mode aerospace_workspace_change

sketchybar --add item app left \
	       --set app script="$PLUGIN_DIR/app.sh" \
		   --subscribe app front_app_switched

# Right side items
sketchybar --add item calendar right \
		   --set calendar update_freq=20 script="$PLUGIN_DIR/calendar.sh"

sketchybar --add item language right \
	       --set language update_freq=5 script="$PLUGIN_DIR/language.sh" \

sketchybar --add item vpn right \
	       --set vpn update_freq=5 script="$PLUGIN_DIR/vpn.sh"

sketchybar --add item volume right \
		   --set volume script="$PLUGIN_DIR/volume.sh" \
		   --subscribe volume volume_change

sketchybar --add item battery right \
	       --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
		   --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
